[build]
  command = "node scripts/version.js"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/book"
  to   = "/book.html"
  status = 200

[[redirects]]
  from = "/admin"
  to   = "/admin.html"
  status = 200

[functions."followup"]
  schedule = "0 17 * * *"
